### PR TITLE
Optimize the iterators by using the same layout as the standard library

### PR DESCRIPTION
**Pull request by Luthaf**
As proposed by @inv2004 in #14 

Could you check if this branch does indeed bring the performances improvement you've seen in your tests ?

TODO: add `DoubleEndedIterator`

### CODE REVIEW

**Comment by inv2004** [comment]
I spent several hour fighting with rust macros, but You did it much faster. Thank you.

Results of benchmasks:

branch = master:
```
running 11 tests
test test_new2_rev_test ... ignored
**test test_iter_opt        ... bench:   1,252,905 ns/iter (+/- 24,436)**
test test_zip             ... bench:     542,700 ns/iter (+/- 10,948)
```

branch = iter-opt:
```
test test_iter_opt        ... bench:     537,483 ns/iter (+/- 10,992)
test test_zip             ... bench:     536,507 ns/iter (+/- 36,289)
```

**Comment by Luthaf** [comment]
Sorry, I did not know you where working on it ... Yes, writing this kind of macros is harder than standard rust, and error reporting is a pain. I usually use `cargo expand` to help me finding errors in the code.

I'll add DoubleEndedIterator and merge this!

**Comment by inv2004** [comment]
not sure if it would help to avoid future problems with complicate iterators built on top of soa-derive.
```
    fn size_hint(&self) -> (usize, Option<usize>) {
      self.0.size_hint()
    }
```

**Comment by Luthaf** [comment]
Do you need this to be released to crates.io ?

**Comment by inv2004** [comment]
Lets wait few weeks. Thank you.

**Pull request merged**
