### PR TITLE
additional derive Deserialize removed from all structs which contains refs

### PR DESCRIPTION
**Pull request by inv2004**
Hello,
It would be good if CheeseVec could be serialized + deserialized.

Now Deserialize derive fails on Slice and Refs during compilation.

Regards,

### CODE REVIEW

**Comment by inv2004** [comment]
No need to pushlish

**Comment by Luthaf** [comment]
This looks good to me. 

Some of the commits in the commit list are the same ones as #10, could you rebase this PR on the top of master ? If you don't know how to do it, I can help.

Generally speaking, it is better to use separated branches for PR.

**Comment by inv2004** [comment]
do not know how to delete this RP. Please do if you can.

**Comment by Luthaf** [comment]
You don't need to submit a new PR to rebase code (but doing so is fine!). Instead, you can force push to the remote branch to update the PR.

**Pull request closed without merging**
